In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
from google.colab import files
uploaded = files.upload()

Saving BA501_python_data.csv to BA501_python_data (1).csv

In [0]:
print (uploaded['BA501_python_data.csv'][:200].decode('utf-8') + '...')

In [0]:
# How do you handle duplicate values in a dataset in Python?

In [12]:
a = np.array([1,2,2,3,3,4,5])
a_dedupe = np.unique(a)
print(a_dedupe)

[1 2 3 4 5]

In [0]:
# Homework 2: You are given two tables - friend_request and request_accepted. Friend_request contains requester_id, time and sent_to_id and request_accepted table contains time, acceptor_id and requestor_id. How will you determine the overall acceptance rate of requests?

In [0]:
select count(a.acceptor_id)/count(r.sent_to_id) from friend_request r left join request_accepted a on a.sent_to_id = r.requestor_id

In [0]:
#Homework 3 “Issuer” of a credit card

In [14]:

friend_request = pd.DataFrame(
    {"requester_id":[1001,1002,1003],
     "time":["2017-07-01","2017-07-02","2017-07-03"],
     "receiver_id":[3001,3002,3003]}
)

request_accepted = pd.DataFrame(
    {"requester_id":[1001,1003],
     "time":["2017-07-01","2017-07-04"],
     "acceptor_id":[3001,3003]}
)

print(friend_request)
print(request_accepted)

   receiver_id  requester_id        time
0         3001          1001  2017-07-01
1         3002          1002  2017-07-02
2         3003          1003  2017-07-03
   acceptor_id  requester_id        time
0         3001          1001  2017-07-01
1         3003          1003  2017-07-04

In [15]:
a = pd.merge(friend_request,request_accepted,how="left",left_on=["requester_id", "receiver_id"], \
             right_on=["requester_id", "acceptor_id"])
len(a["acceptor_id"][a.acceptor_id > 0])/(len(a["acceptor_id"])*1.0)

0.6666666666666666

In [0]:
#SQL
select
T1.date,
sum(if(t2.acceptor_id is null, 0, 1))/sum(t1.request_id) as acceptance_rate
from friend_request t1
left join request_accepted t2
on t1.requester_id=t2.requeter_id
and T1.receiver_id=T2.acceptor_id
group by t1.request_id;

In [0]:
#homework 3 credit cart issuers

In [0]:
my_cc = ['4175004175004172', 
'4917491749174917',
'346416800707698',
'376416800707698',
'37641680070769832112',
'36641680070769',
'54545641680070769']

In [29]:
def issuer_detector(cc):
    # amex
    if len(cc) == 15 and (cc[0:2]=='34' or cc[0:2]=='37'):
        return "AMEX"
    # diners club
    if len(cc)==14 and cc[0:2]=='36':
        return "DINERS CLUB"
    # visa
    if len(cc)==16 and cc[0:1]=='4':
        if cc[0:4] == "4026" \
            or cc[0:4] == "4405" \
            or cc[0:4] == "4408" \
            or cc[0:4] == "4844" \
            or cc[0:4] == "4913" \
            or cc[0:6] == "417500":
            return "VISAELECTRON"
        else:
            return "VISA"
    else:
        return "NA"

for cc in my_cc:
    print (cc + " " + issuer_detector(cc))

4175004175004172 VISAELECTRON
4917491749174917 VISA
346416800707698 AMEX
376416800707698 AMEX
37641680070769832112 NA
36641680070769 DINERS CLUB
54545641680070769 NA

In [30]:
from google.colab import files
uploaded = files.upload()

Saving BA501_python_data.csv to BA501_python_data (2).csv

In [32]:
import pandas as pd
import io

df = pd.read_csv(io.StringIO(uploaded['BA501_python_data.csv'].decode('utf-8')))
df

,country,date,experiment_id,order_id,spend_usd,user_id,vertical
0,JP,20170402,12624548,5813140433216629693,16.138855,5006730028073359543,ANDROID_APPS
1,US,20170403,12624549,16333056276711034931,9.990000,5938685669571545259,ANDROID_APPS
2,JP,20170404,12624548,11227119161741298366,19.887087,17623708458399141713,ANDROID_APPS
3,US,20170403,12624548,11927299833124210932,19.990000,18042812344456618148,ANDROID_APPS
4,JP,20170403,12624549,11644727017708872749,88.220093,4325104700699531031,ANDROID_APPS
5,FR,20170406,12624548,2887851716418524034,10.641677,15563614621402392174,ANDROID_APPS
6,US,20170406,12624548,8835194413765780524,9.990000,793284520969747371,ANDROID_APPS
7,US,20170402,12624549,2761291987218019434,10.090000,4877509876568871706,MUSIC
8,US,20170405,12624548,9027895522629963459,9.990000,3647559719307779196,ANDROID_APPS
9,US,20170405,12624548,2588200289165850850,19.990000,3647559719307779196,ANDROID_APPS
10,KR,20170402,12624548,163542271130138050,1.967007,234343989879687882,ANDROID_APPS
11,KR,20170402,12624548,18314448354305184003,1.967007,234343989879687882,ANDROID_APPS
12,JP,20170402,12624549,1931426249776431110,5.379618,1925282073030462007,ANDROID_APPS
13,US,20170402,12624549,16273876950050275625,10.670000,2825758151779042993,MUSIC
14,US,20170407,12624548,10840886354488278741,1.990000,9548909044371812783,ANDROID_APPS
15,US,20170407,12624548,13509704498549969641,1.990000,9548909044371812783,ANDROID_APPS
16,FR,20170404,12624548,10156729419384894204,2.122063,7177229992970966269,ANDROID_APPS
17,US,20170401,12624549,17866604156934800547,9.990000,17061805777408420188,ANDROID_APPS
18,US,20170401,12624549,17172758733364150210,4.990000,17061805777408420188,ANDROID_APPS
19,US,20170401,12624549,4309427141110727791,9.990000,17061805777408420188,ANDROID_APPS
20,US,20170401,12624549,13054750004532361873,4.990000,17061805777408420188,ANDROID_APPS
21,US,20170401,12624549,9668472000207734522,19.990000,17061805777408420188,ANDROID_APPS
22,ID,20170404,12624549,17859748408594464317,0.900209,9149768684639718630,ANDROID_APPS
23,GB,20170407,12624548,16447787927329176121,2.467122,8194296029841078338,ANDROID_APPS
24,GB,20170402,12624549,9711595975487748780,4.993586,3196750080339569107,ANDROID_APPS
25,GB,20170407,12624549,13108513329546069822,2.219170,3196750080339569107,ANDROID_APPS
26,US,20170406,12624548,15497417806611168788,9.990000,11852286259447629475,ANDROID_APPS
27,IT,20170401,12624548,14694857484980201220,2.123837,13600555877110054452,ANDROID_APPS
28,IT,20170402,12624548,8457069893257724816,2.123837,13600555877110054452,ANDROID_APPS
29,BR,20170407,12624549,3710803681919434513,3.771692,4131707298051750259,ANDROID_APPS
...,...,...,...,...,...,...,...
73880,US,20170403,12624549,10151380505257442492,1.990000,8421951665437654655,ANDROID_APPS
73881,US,20170403,12624549,14504947818282790070,4.990000,8421951665437654655,ANDROID_APPS
73882,US,20170401,12624549,13840822139616650734,0.990000,5277118335645791322,ANDROID_APPS
73883,US,20170401,12624549,5530185573679841844,0.990000,5277118335645791322,ANDROID_APPS
73884,US,20170401,12624549,311177774074213914,0.990000,5277118335645791322,ANDROID_APPS
73885,US,20170407,12624549,11159257956065032706,6.990000,5277118335645791322,ANDROID_APPS
73886,US,20170401,12624549,8624375232262768315,0.990000,5277118335645791322,ANDROID_APPS
73887,US,20170407,12624549,7664945592309141443,0.990000,5277118335645791322,ANDROID_APPS
73888,US,20170404,12624549,6348049333301399287,0.990000,5277118335645791322,ANDROID_APPS
73889,US,20170407,12624549,16872300785315309183,0.990000,5277118335645791322,ANDROID_APPS
73890,US,20170405,12624549,17536989754197573108,0.990000,5277118335645791322,ANDROID_APPS
73891,US,20170407,12624549,6303493244147022522,0.990000,5277118335645791322,ANDROID_APPS
73892,US,20170407,12624549,9046847135016571186,0.990000,5277118335645791322,ANDROID_APPS
73893,US,20170407,12624549,16245868508862016855,0.990000,5277118335645791322,ANDROID_APPS
73894,US,20170405,12624549,2562112628384373625,0.990000,5277118335645791322,ANDROID_APPS
73895,US,20170401,12624549,8161308829430752838,0.990000,5277118335645791322,ANDROID_APPS
73896,US,20170401,12624549,7480378351676032504,0.990000,5277118335645791322,ANDROID_APPS
73897,US,20170403,12624548,16483215756500408423,1.070000,2037177391099801444,ANDROID_APPS
73898,JP,20170402,12624548,14014033083882804398,3.227771,3929662943179788569,ANDROID_APPS
73899,JP,20170402,12624548,4351357150330387082,8.607389,3929662943179788569,ANDROID_APPS
73900,JP,20170404,12624548,3592277135384909432,32.478030,11552720349904444535,ANDROID_APPS
73901,JP,20170403,12624548,12418470914692041327,32.407381,11552720349904444535,ANDROID_APPS
73902,US,20170407,12624548,11639753371766987819,9.990000,7071947499862829843,MUSIC
73903,US,20170403,12624548,15284184602018149137,10.640000,2531844752389960958,ANDROID_APPS
73904,US,20170402,12624549,9812307515499620375,7.990000,1912197141410583360,YOUTUBE
73905,US,20170403,12624548,8529754119075378513,16.110000,3353613577305273816,ANDROID_APPS
73906,US,20170402,12624549,1545393608203752248,5.000000,6046493884787456084,MULTI_CONTAINER
73907,US,20170402,12624549,15597374315984713350,19.990000,6046493884787456084,YOUTUBE
73908,KR,20170402,12624548,1813806410976065581,7.868031,15940200285922588837,ANDROID_APPS
73909,JP,20170402,12624548,14938275805862501568,2.062187,2801009977600674803,ANDROID_APPS

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [0]:
my_data = pd.read_csv('BA501_python_data.csv')

In [22]:
my_data.head(5)

,country,date,experiment_id,order_id,spend_usd,user_id,vertical
0,JP,20170402,12624548,5813140433216629693,16.138855,5006730028073359543,ANDROID_APPS
1,US,20170403,12624549,16333056276711034931,9.990000,5938685669571545259,ANDROID_APPS
2,JP,20170404,12624548,11227119161741298366,19.887087,17623708458399141713,ANDROID_APPS
3,US,20170403,12624548,11927299833124210932,19.990000,18042812344456618148,ANDROID_APPS
4,JP,20170403,12624549,11644727017708872749,88.220093,4325104700699531031,ANDROID_APPS

In [0]:
my_data.date = pd.to_datetime(my_data.date, format='%Y%m%d')

In [24]:
my_data.head(5)

,country,date,experiment_id,order_id,spend_usd,user_id,vertical
0,JP,2017-04-02,12624548,5813140433216629693,16.138855,5006730028073359543,ANDROID_APPS
1,US,2017-04-03,12624549,16333056276711034931,9.990000,5938685669571545259,ANDROID_APPS
2,JP,2017-04-04,12624548,11227119161741298366,19.887087,17623708458399141713,ANDROID_APPS
3,US,2017-04-03,12624548,11927299833124210932,19.990000,18042812344456618148,ANDROID_APPS
4,JP,2017-04-03,12624549,11644727017708872749,88.220093,4325104700699531031,ANDROID_APPS

In [0]:
my_id = 12624548
country="US"
table = my_data[["date", "spend_usd"]][(my_data.experiment_id == my_id) & (my_data.country == country)]

In [0]:
my_data = pd.read_csv('BA501_python_data.csv')

In [0]:
def GetCumulativeSeries(my_data, my_id, country):
    table = my_data[["date", "spend_usd"]][(my_data.experiment_id == my_id) & (my_data.country == country)]
    series = table.groupby('date')['spend_usd'].sum() 
    series = np.cumsum(series) 
    total_revenue = series[-1]
    return((series, total_revenue))


def PlotSeries(experiment_series, control_series):
    fig, ax = plt.subplots()
    ax.plot(experiment_series, color="red", label="experiment")
    ax.plot(control_series, color="blue", label="control")
    ax.set_title("Red vs. Blue")
    ax.set_ylabel("Total spend")
    ax.grid(True, which="both")
    ax.legend()
    plt.gcf().autofmt_xdate()
    
def PrintCumulativeTimeSeries(my_data, experiment_ids, country):

    my_data = my_data.sort_values("date", ascending=True, inplace=False)
    treatment_series = GetCumulativeSeries(my_data, experiment_ids[0], country)[0]
    treatment_revenue = GetCumulativeSeries(my_data, experiment_ids[0], country)[1]
    control_series = GetCumulativeSeries(my_data, experiment_ids[1], country)[0]
    control_revenue = GetCumulativeSeries(my_data, experiment_ids[1], country)[1]
    
    print("Cumulative revenue impact: " + str(treatment_revenue/control_revenue*100-100) + "%")
    PlotSeries(treatment_series, control_series)

    PrintCumulativeTimeSeries(my_data, [12624548,12624549], "JP")